CREATE ROLE "<database-name>";

CREATE USER "<database-name>" PASSWORD = '<password>' 
LOGIN_NAME='<database-name>' DISPLAY_NAME = '<database-name>' FIRST_NAME = 'S3Snowflake' 
LAST_NAME = 'Tester' 
EMAIL= 's3snowflake.tester@domain.com' MUST_CHANGE_PASSWORD=FALSE DEFAULT_ROLE="<database-name>"; 

GRANT ROLE "<database-name>" TO USER "<database-name>";

GRANT ROLE "<database-name>" TO ROLE "<role-name>";

CREATE DATABASE "<database-name>";

GRANT ALL PRIVILEGES ON DATABASE "<database-name>"  TO ROLE "<database-name>";

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE "<database-name>" TO ROLE "<database-name>";

GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE "<database-name>" TO ROLE "<database-name>";

GRANT USAGE ON WAREHOUSE "<role-name>" TO ROLE "<database-name>" WITH GRANT OPTION;

CREATE OR REPLACE FILE FORMAT "<database-name>"."PUBLIC"."PARQUET_FORMAT" TYPE = 'parquet' COMPRESSION = 'AUTO' 
COMMENT = '#' BINARY_AS_TEXT = TRUE;

CREATE OR REPLACE FILE FORMAT "<database-name>"."PUBLIC"."JSON_FORMAT" TYPE = 'json' COMMENT = '#';

CREATE OR REPLACE FILE FORMAT "<database-name>"."PUBLIC"."CSV_COMMA_FORMAT" TYPE = 'csv' 
COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' COMMENT = '#' SKIP_HEADER = 0 
FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');

CREATE OR REPLACE FILE FORMAT "<database-name>"."PUBLIC"."CSV_TAB_FORMAT" TYPE = 'csv' 
COMPRESSION = 'AUTO' FIELD_DELIMITER = '\t' RECORD_DELIMITER = '\n' COMMENT = '#' SKIP_HEADER = 0 
FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');

CREATE OR REPLACE FILE FORMAT "<database-name>"."PUBLIC"."CSV_PIPE_FORMAT" TYPE = 'csv' 
COMPRESSION = 'AUTO' FIELD_DELIMITER = '|' RECORD_DELIMITER = '\n' COMMENT = '#' SKIP_HEADER = 0 
FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE'
ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');

GRANT USAGE ON FILE FORMAT "<database-name>"."PUBLIC"."PARQUET_FORMAT" TO ROLE "<database-name>" WITH GRANT OPTION;

GRANT USAGE ON FILE FORMAT "<database-name>"."PUBLIC"."CSV_COMMA_FORMAT" TO ROLE "<database-name>" WITH GRANT OPTION;

GRANT USAGE ON FILE FORMAT "<database-name>"."PUBLIC"."CSV_TAB_FORMAT" TO ROLE "<database-name>" WITH GRANT OPTION;

GRANT USAGE ON FILE FORMAT "<database-name>"."PUBLIC"."CSV_PIPE_FORMAT" TO ROLE "<database-name>" WITH GRANT OPTION;

ALTER DATABASE "<database-name>" SET DATA_RETENTION_TIME_IN_DAYS = 0 MAX_DATA_EXTENSION_TIME_IN_DAYS = 90;

alter user "<database-name>" set 
rsa_public_key='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimeP3EaLMrPUS6bunuAhVOFYVrqWKYuTAucr0oJ26K6Bwv417e1Kn7ZzoQfJRkFRRLmQS/A1BHzQcaJaWjrQPh1/173ntlbL6lIkSjGkBpd3hdS1a00dCd+glWlxjeSJ2k+eHXnYrQt9YX7RIPX3E0wcKBOwuKOsK4Vb0HJH9XgiW0TOChZLEVEHwBDPA/rgg5PI7ft7bEK3iVtAgSwp0LobOlOzbADPHBcL/9FQYC7oXOKh2bGRstQtVUtnQoMP5isN6PSBTKs1AwH8wWZhcQku9QgYqZi6d3WKUsVNcTUtU4HA7DYtqezZoWUgorGdZimqgZRpZvLNrcvPiNsqqQIDAQAB';